# Default values for project-baobab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/teamorea/project-baobab
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
- name: SQLALCHEMY_TRACK_MODIFICATIONS
  value: 'False'
- name: PORT
  value: '3000'
- name: SQLALCHEMY_DATABASE_URI
  valueFrom:
    secretKeyRef:
      name: project-baobab
      key: SQLALCHEMY_DATABASE_URI

podSecurityContext:
  fsGroup: 101

imagePullSecrets:
- name: ghcr-credentials

service:
  type: ClusterIP
  port: 80
  externalPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts: []

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

secrets:
  SQLALCHEMY_DATABASE_URI: "" # enter database URL here in the format 'postgresql://user:password@host:port/database'

GHCR_auth_json: "" # this should be in the format '{"auths":{"ghcr.io":{"auth":"username:token | base64"}}}'
