services:
  web:
    build: .
    command: sh -c "flask db upgrade && gunicorn -w 2 -b 0.0.0.0:3000 app:app"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: