services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  postgres_data:
