{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-baobab.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc }}
    {{- end }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: {{ .Release.Namespace }}
data:
    .dockerconfigjson: {{ .Values.GHCR_auth_json | b64enc }}
type: kubernetes.io/dockerconfigjson
