name: Build Docker Image and Create Helm Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/teamorea/leyline-api:${{ github.sha }} \
          --tag ghcr.io/teamorea/leyline-api:latest \
          --push .

    # - name: Package Helm chart
    #   run: |
    #     cd kubernetes/leyline-api/
    #     helm package .

    # - name: Upload Helm chart as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: helm-chart
    #     path: kubernetes/leyline-api/*.tgz
  publish:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"  
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.2

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GHCR_TOKEN }}"
